
export const coursesList = {
    "$.0.0": "Mathematics",
    "$.0.1": "Physics",
    "$.0.2": "Chemistry",
    "$.0.3": "Biology",
    "$.0.4": "Computer Science",
    "$.0.5": "Engineering(various disciplines)",
    "$.0.6": "Psychology",
    "$.0.7": "Economics",
    "$.0.8": "Business Administration",
    "$.0.9": "History",
    "$.0.10": "Political Science",
    "$.0.11": "Sociology",
    "$.0.12": "Literature",
    "$.0.13": "Philosophy",
    "$.0.14": "Art History",
    "$.0.15": "Music",
    "$.0.16": "Environmental Science",
    "$.0.17": "Geology",
    "$.0.18": "Astronomy",
    "$.0.19": "Medicine",
    "$.0.20": "Nursing",
    "$.0.21": "Law",
    "$.0.22": "Education",
    "$.0.23": "Architecture",
    "$.0.24": "Linguistics",
    "$.0.25": "Communication Studies",
    "$.0.26": "Anthropology",
    "$.0.27": "Agriculture",
    "$.0.28": "Food Science",
    "$.0.29": "Forestry",
    "$.0.30": "Journalism",
    "$.0.31": "Library Science",
    "$.0.32": "Public Administration",
    "$.0.33": "Social Work",
    "$.0.34": "Urban Planning",
    "$.0.35": "Other"
} as Record<string, string>;


