FROM node:20-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY . .

RUN npm install --f 

# Build the app
RUN npm run build

# Expose the portR
EXPOSE 3000

# Start the app
CMD [ "npm", "start" ]



