import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '../pages/layout/Header'
import { Providers } from '@/themeProvider/Provider'
import { Toaster } from "react-hot-toast";
import SideBar from '@/pages/layout/SideBar'
import AskModal from '@/pages/modals/questionModal/AskModal'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Campus Commune',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='light'>
      <body className={inter.className}>
        <Providers>
          <Toaster position="top-center" reverseOrder={false} />
          <AskModal />
          <Header />
          <SideBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
